language: python
python:
  - "3.7"
install:
  - pip install .
before_script:
  - pip install pep8 pytest-cov coveralls
script:
  - pep8 factorgraph/ tests/
  - py.test --cov=factorgraph tests/
after_success:
  - coveralls
